--------------------------------------------------------
--  File creato - venerdì-gennaio-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TDS00_SFDC_INPUT
--------------------------------------------------------

  CREATE TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" 
   (	"DS00_RUN_GUID" VARCHAR2(32) NOT NULL ENABLE, 
	"DS00_RUN_STAT" VARCHAR2(32) NOT NULL ENABLE, 
	"DS00_CRTN_DATE" DATE NOT NULL ENABLE, 
	"DS00_SEND_DATE" DATE, 
	"DS00_MODF_DATE" DATE NOT NULL ENABLE, 
	"DS00_DATA_TYP" VARCHAR2(20) NOT NULL ENABLE, 
	"DS00_DATA_VAL" VARCHAR2(200) NOT NULL ENABLE, 
	"DS00_OPER_VAL" VARCHAR2(2) NOT NULL ENABLE, 
	"DS00_SRC_COD" VARCHAR2(5), 
	 CONSTRAINT "TDS00_OPER_VAL" CHECK (DS00_OPER_VAL IN ('=', '!=', '>', '<', '>=', '<=')) ENABLE, 
	 CONSTRAINT "TDS00_RUN_STAT" CHECK (DS00_RUN_STAT IN ('DRAFT', 'NEW', 'PENDING', 'QUEUED', 'READING', 'WORKING', 'DONE', 'FAILED')) ENABLE, 
	 CONSTRAINT "TDS00_DATA_TYP" CHECK (DS00_DATA_TYP IN ('SIGLE', 'AGENTE', 'FILIALE', 'LAV_AGT', 'LAV_FIL', 'COMM', 'QUERY')) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 104857600 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCC1DD01"
--------------------------------------------------------
--  DDL for Table TDS02_PARAMS
--------------------------------------------------------

  CREATE TABLE "DBA_DBCC1"."TDS02_PARAMS" 
   (	"DS02_PARM_COD" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"DS02_PARM_DES" VARCHAR2(100 CHAR), 
	"DS02_PARM_VAL" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"DS02_MODF_DTA" DATE, 
	 CONSTRAINT "IDS02_P01" PRIMARY KEY ("DS02_PARM_COD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TEMPORANEE"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TEMPORANEE"
--------------------------------------------------------
--  Constraints for Table TDS00_SFDC_INPUT
--------------------------------------------------------

  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" MODIFY ("DS00_RUN_GUID" NOT NULL ENABLE)
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" MODIFY ("DS00_RUN_STAT" NOT NULL ENABLE)
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" MODIFY ("DS00_CRTN_DATE" NOT NULL ENABLE)
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" MODIFY ("DS00_MODF_DATE" NOT NULL ENABLE)
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" MODIFY ("DS00_DATA_TYP" NOT NULL ENABLE)
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" MODIFY ("DS00_DATA_VAL" NOT NULL ENABLE)
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" MODIFY ("DS00_OPER_VAL" NOT NULL ENABLE)
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" ADD CONSTRAINT "TDS00_DATA_TYP" CHECK (DS00_DATA_TYP IN ('SIGLE', 'AGENTE', 'FILIALE', 'LAV_AGT', 'LAV_FIL', 'COMM', 'QUERY')) ENABLE
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" ADD CONSTRAINT "TDS00_OPER_VAL" CHECK (DS00_OPER_VAL IN ('=', '!=', '>', '<', '>=', '<=')) ENABLE
 
  ALTER TABLE "DBA_DBCC1"."TDS00_SFDC_INPUT" ADD CONSTRAINT "TDS00_RUN_STAT" CHECK (DS00_RUN_STAT IN ('DRAFT', 'NEW', 'PENDING', 'QUEUED', 'READING', 'WORKING', 'DONE', 'FAILED')) ENABLE
