--------------------------------------------------------
--  File creato - venerdì-gennaio-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TCD0M_VALID_TRNS
--------------------------------------------------------

  CREATE TABLE "DBACD1CDB"."TCD0M_VALID_TRNS" 
   (	"CD0M_RAW_XID_DES" RAW(8) NOT NULL ENABLE, 
	"CD0M_PROG_TRNS_DES" VARCHAR2(3) NOT NULL ENABLE, 
	"CD0M_VALID_FLG" CHAR(1), 
	"CD0M_CALC_DTA" DATE, 
	 CONSTRAINT "ICD0M_P01" PRIMARY KEY ("CD0M_RAW_XID_DES", "CD0M_PROG_TRNS_DES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCD1DA01"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCD1DA01"
  GRANT DELETE ON "DBACD1CDB"."TCD0M_VALID_TRNS" TO "DBACD8ESB"
 
  GRANT INSERT ON "DBACD1CDB"."TCD0M_VALID_TRNS" TO "DBACD8ESB"
 
  GRANT SELECT ON "DBACD1CDB"."TCD0M_VALID_TRNS" TO "DBACD8ESB"
 
  GRANT UPDATE ON "DBACD1CDB"."TCD0M_VALID_TRNS" TO "DBACD8ESB"
--------------------------------------------------------
--  DDL for Index ICD0M_P01
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBACD1CDB"."ICD0M_P01" ON "DBACD1CDB"."TCD0M_VALID_TRNS" ("CD0M_RAW_XID_DES", "CD0M_PROG_TRNS_DES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCD1DA01"
--------------------------------------------------------
--  DDL for Index ICD0M_VALID_TRNS_IDX02
--------------------------------------------------------

  CREATE INDEX "DBACD1CDB"."ICD0M_VALID_TRNS_IDX02" ON "DBACD1CDB"."TCD0M_VALID_TRNS" (RAWTOHEX("CD0M_RAW_XID_DES")||"CD0M_PROG_TRNS_DES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCD1DA01"
--------------------------------------------------------
--  Constraints for Table TCD0M_VALID_TRNS
--------------------------------------------------------

  ALTER TABLE "DBACD1CDB"."TCD0M_VALID_TRNS" ADD CONSTRAINT "ICD0M_P01" PRIMARY KEY ("CD0M_RAW_XID_DES", "CD0M_PROG_TRNS_DES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCD1DA01"  ENABLE
 
  ALTER TABLE "DBACD1CDB"."TCD0M_VALID_TRNS" MODIFY ("CD0M_RAW_XID_DES" NOT NULL ENABLE)
 
  ALTER TABLE "DBACD1CDB"."TCD0M_VALID_TRNS" MODIFY ("CD0M_PROG_TRNS_DES" NOT NULL ENABLE)
