--------------------------------------------------------
--  File creato - venerdì-gennaio-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Function COMPARECELL
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "DBACD8ESB"."COMPARECELL" ( guid in CDB_CONFRONTO_DETT.CD02_RUN_GUID%TYPE, customerId CDB_CONFRONTO_DETT.CODICE_CUSTOMER__C%TYPE, codiceSede CDB_CONFRONTO_DETT.CODICE_SEDE__C%TYPE, columnName VARCHAR )
RETURN CHAR
AS 
    result 			CHAR;
    sfData 			VARCHAR(200);
    cdbData			VARCHAR(200);
    existsSfRow 	INT;
    existsCdbRow 	INT;
    query			VARCHAR(4000);
    
BEGIN 

	SELECT '0' INTO result FROM DUAL;
	
	SELECT 'SELECT ' || columnName || ' FROM DBACD8ESB.CDB_CONFRONTO_DETT WHERE CD02_RUN_GUID = '''||guid||''' AND CODICE_CUSTOMER__C = '''||customerId||''' AND CODICE_SEDE__C = '''||codiceSede||''' AND CD02_TIPO_DIFF = ''0''' INTO query FROM DUAL;
	
	SELECT count(*) INTO existsSfRow
	FROM DBACD8ESB.CDB_CONFRONTO_DETT
	WHERE CD02_RUN_GUID = guid
	AND CODICE_CUSTOMER__C = customerId
	AND CODICE_SEDE__C = codiceSede
	AND CD02_TIPO_DIFF = '0'
	AND CD02_SOURCE = 'SF';
	
	SELECT count(*) INTO existsCdbRow
	FROM DBACD8ESB.CDB_CONFRONTO_DETT
	WHERE CD02_RUN_GUID = guid
	AND CODICE_CUSTOMER__C = customerId
	AND CODICE_SEDE__C = codiceSede
	AND CD02_TIPO_DIFF = '0'
	AND CD02_SOURCE = 'CDB';
	
	IF ( existsSfRow <> 1 OR existsCdbRow <> 1 ) THEN
	BEGIN
		RETURN '0';
	END;
	END IF;

    EXECUTE IMMEDIATE (query||' and CD02_SOURCE = ''SF''') INTO sfData;
	
	EXECUTE IMMEDIATE (query||' and CD02_SOURCE = ''CDB''') INTO cdbData;
	
	SELECT CASE WHEN cdbData IS NULL AND sfData IS NULL THEN '1' WHEN sfData = cdbData THEN '1' ELSE '0' END INTO result FROM DUAL;
	
    return (result); -- '0' -> diversi, '1' -> uguali
END;
--------------------------------------------------------
--  DDL for Function COMPAREROWS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "DBACD8ESB"."COMPAREROWS" ( guid in CDB_CONFRONTO_DETT.CD02_RUN_GUID%TYPE, customerId CDB_CONFRONTO_DETT.CODICE_CUSTOMER__C%TYPE, codiceSede CDB_CONFRONTO_DETT.CODICE_SEDE__C%type )
RETURN CHAR
AS 
    result 			CHAR;
    sfRow 			VARCHAR(4000);
    cdbRow			VARCHAR(4000);
    existsSfRow 	INT;
    existsCdbRow 	INT;
    
BEGIN 

	SELECT '0' INTO result FROM DUAL;
	
	SELECT count(*) INTO existsSfRow
	FROM DBACD8ESB.CDB_CONFRONTO_DETT
	WHERE CD02_RUN_GUID = guid
	AND CODICE_CUSTOMER__C = customerId
	AND CODICE_SEDE__C = codiceSede
	AND CD02_TIPO_DIFF = '0'
	AND CD02_SOURCE = 'SF';
	
	SELECT count(*) INTO existsCdbRow
	FROM DBACD8ESB.CDB_CONFRONTO_DETT
	WHERE CD02_RUN_GUID = guid
	AND CODICE_CUSTOMER__C = customerId
	AND CODICE_SEDE__C = codiceSede
	AND CD02_TIPO_DIFF = '0'
	AND CD02_SOURCE = 'CDB';
	
	IF ( existsSfRow <> 1 OR existsCdbRow <> 1 ) THEN
	BEGIN
		RETURN '0';
	END;
	END IF;

    SELECT ANNO_FONDAZIONE__C||FORMATNUMBER(ANNUALREVENUE)||BILLINGCITY||BILLINGCOUNTRY||BILLINGSTATE||BILLINGSTREET||CAP__C||CELLULA__C||CODICE_COMUNE_IOL__C||CODICE_CUSTOMER__C||CODICE_FRAZIONE__C||CODICE_IPA__C||CODICE_PROVINCIA_REA__C||CODICE_SEDE__C||CODICE_STATO_CUSTOMER__C||CODICE_STATO_SEDE__C||CODICEFISCALE__C||COMUNE_IOL__C||FORMATNUMBER(COORD_ANAG__LATITUDE__S)||FORMATNUMBER(COORD_ANAG__LONGITUDE__S)||COORDINATE_MANUALI__C||DATO_FISC_EST_CERT__C||DUG__C||EMAIL_ARRICCHIMENTO__C||FORMATNUMBER(EMAIL_ARRICCHIMENTO_ID__C)||EMAIL_BOZZE__C||FORMATNUMBER(EMAIL_BOZZE_ID__C)||EMAIL_COMMERCIALE_IOL__C||FORMATNUMBER(EMAIL_COMMERCIALE_IOL_ID__C)||EMAIL_FATTURAZIONE__C||FORMATNUMBER(EMAIL_FATTURAZIONE_ID__C)||EMAIL_POST_VENDITA__C||FORMATNUMBER(EMAIL_POST_VENDITA_ID__C)||ENTE_PUBBLICO__C||FATTURAZIONE_COD_FISC__C||FATT_ELETTR_OBBLIGATORIA__C||FRAZIONE__C||ID||INDUSTRY||INFO_TOPONIMO__C||INSEGNA__C||IOL_ANNOFATTURATO__C||IOL_ANNORIFDIPENDENTI__C||IOL_BILLINGCOUNTRYCOD__C||IOL_BUONOORDINE__C||IOL_CATEGORIA__C||IOL_CATEGORIAISTAT__C||IOL_CATEGORIAMERCEOLOGICA__C||IOL_CLASSIFICAZIONEPMI__C||IOL_CODICEAREAELENCO__C||IOL_CODICECATEGORIAISTAT__C||IOL_CODCATEGMERCEOLOGICA__C||IOL_CODCATEGMERCMAXSPESA__C||IOL_CODICECUSTOMER_OLD__C||IOL_CODINDICCLIENTISPEC__C||IOL_CODICESEDE_OLD__C||IOL_COGNOMEPERSONAFISICA__C||IOL_CUSTCESSRIAT__C||IOL_CUSTOMERCOUNTRYCOD__C||IOL_EMAIL_ARR_PEC__C||IOL_EMAIL_BOZZE_PEC__C||IOL_EMAIL_COMM_IOL_PEC__C||IOL_EMAIL_FATTURAZIONE_PEC__C||IOL_EMAIL_POST_VENDITA_PEC__C||FORMATNUMBER(IOL_INDIRIZZOID__C)||IOL_MERCATOAGGREGATO__C||IOL_NOMEPERSONAFISICA__C||IOL_NUMEROREA__C||IOL_OPECCONSEGNABILE__C||IOL_POTENZIALENIP__C||IOL_SEDECESSRIATT_C||IOL_SOTTOAREAMERCATO__C||IOL_SOTTOCLASSEDIPENDENTI__C||IOL_SOTTOCLASSEFATTURATO__C||IOL_TIPOMERCATO__C||NAME||NAZIONE__C||NOTE_SUL_RECAPITO_FATTURA__C||FORMATNUMBER(NUMBEROFEMPLOYEES)||NUMERO_CIVICO__C||OPEC__C||PARTITAIVA__C||PHONE||PRIMARIO1__C||PRIMARIO2__C||PRIMARIO3__C||PRIMARIO4__C||PRIMARIO5__C||PRIMARIO6__C||PRIMARIO7__C||PRIMARIO8__C||PROF_COORD_ANAGRAFICHE__C||PROVINCIA_IOL__C||SEDE_PRIMARIA_OPEC__C||FORMATNUMBER(TELEFONO_1_ID__C)||FORMATNUMBER(TELEFONO_2_ID__C)||FORMATNUMBER(TELEFONO_3_ID__C)||FORMATNUMBER(TELEFONO_4_ID__C)||FORMATNUMBER(TELEFONO_5_ID__C)||FORMATNUMBER(TELEFONO_6_ID__C)||FORMATNUMBER(TELEFONO_7_ID__C)||FORMATNUMBER(TELEFONO_8_ID__C)||TELEFONO2__C||TELEFONO3__C||TELEFONO4__C||TELEFONO5__C||TELEFONO6__C||TELEFONO7__C||TELEFONO8__C||TIPO_PERSONA_GIURIDICA__C||TIPO_SOCIETA_GIURIDICA__C||TIPOLOGIATELEFONO1__C||TIPOLOGIATELEFONO2__C||TIPOLOGIATELEFONO3__C||TIPOLOGIATELEFONO4__C||TIPOLOGIATELEFONO5__C||TIPOLOGIATELEFONO6__C||TIPOLOGIATELEFONO7__C||TIPOLOGIATELEFONO8__C||TOPONIMO__C||TYPESOC||ULT_POS_AMMINSTRATIVA__C||URL_FANPAGE__C||URL_ID_FANPAGE__C||URL_ID_ISTITUZIONALE__C||URL_ID_PAGINE_BIANCHE__C||URL_ID_PAGINE_GIALLE__C||URL_PAGINE_BIANCHE__C||URL_PAGINE_GIALLE__C||WEBSITE
	INTO sfRow
	FROM DBACD8ESB.CDB_CONFRONTO_DETT
	WHERE CD02_RUN_GUID = guid
	AND CODICE_CUSTOMER__C = customerId
	AND CODICE_SEDE__C = codiceSede
	AND CD02_TIPO_DIFF = '0'
	AND CD02_SOURCE = 'SF';
	
	SELECT ANNO_FONDAZIONE__C||ANNUALREVENUE||BILLINGCITY||BILLINGCOUNTRY||BILLINGSTATE||BILLINGSTREET||CAP__C||CELLULA__C||CODICE_COMUNE_IOL__C||CODICE_CUSTOMER__C||CODICE_FRAZIONE__C||CODICE_IPA__C||CODICE_PROVINCIA_REA__C||CODICE_SEDE__C||CODICE_STATO_CUSTOMER__C||CODICE_STATO_SEDE__C||CODICEFISCALE__C||COMUNE_IOL__C||COORD_ANAG__LATITUDE__S||COORD_ANAG__LONGITUDE__S||COORDINATE_MANUALI__C||DATO_FISC_EST_CERT__C||DUG__C||EMAIL_ARRICCHIMENTO__C||EMAIL_ARRICCHIMENTO_ID__C||EMAIL_BOZZE__C||EMAIL_BOZZE_ID__C||EMAIL_COMMERCIALE_IOL__C||EMAIL_COMMERCIALE_IOL_ID__C||EMAIL_FATTURAZIONE__C||EMAIL_FATTURAZIONE_ID__C||EMAIL_POST_VENDITA__C||EMAIL_POST_VENDITA_ID__C||ENTE_PUBBLICO__C||FATTURAZIONE_COD_FISC__C||FATT_ELETTR_OBBLIGATORIA__C||FRAZIONE__C||ID||INDUSTRY||INFO_TOPONIMO__C||INSEGNA__C||IOL_ANNOFATTURATO__C||IOL_ANNORIFDIPENDENTI__C||IOL_BILLINGCOUNTRYCOD__C||IOL_BUONOORDINE__C||IOL_CATEGORIA__C||IOL_CATEGORIAISTAT__C||IOL_CATEGORIAMERCEOLOGICA__C||IOL_CLASSIFICAZIONEPMI__C||IOL_CODICEAREAELENCO__C||IOL_CODICECATEGORIAISTAT__C||IOL_CODCATEGMERCEOLOGICA__C||IOL_CODCATEGMERCMAXSPESA__C||IOL_CODICECUSTOMER_OLD__C||IOL_CODINDICCLIENTISPEC__C||IOL_CODICESEDE_OLD__C||IOL_COGNOMEPERSONAFISICA__C||IOL_CUSTCESSRIAT__C||IOL_CUSTOMERCOUNTRYCOD__C||IOL_EMAIL_ARR_PEC__C||IOL_EMAIL_BOZZE_PEC__C||IOL_EMAIL_COMM_IOL_PEC__C||IOL_EMAIL_FATTURAZIONE_PEC__C||IOL_EMAIL_POST_VENDITA_PEC__C||IOL_INDIRIZZOID__C||IOL_MERCATOAGGREGATO__C||IOL_NOMEPERSONAFISICA__C||IOL_NUMEROREA__C||IOL_OPECCONSEGNABILE__C||IOL_POTENZIALENIP__C||IOL_SEDECESSRIATT_C||IOL_SOTTOAREAMERCATO__C||IOL_SOTTOCLASSEDIPENDENTI__C||IOL_SOTTOCLASSEFATTURATO__C||IOL_TIPOMERCATO__C||NAME||NAZIONE__C||NOTE_SUL_RECAPITO_FATTURA__C||NUMBEROFEMPLOYEES||NUMERO_CIVICO__C||OPEC__C||PARTITAIVA__C||PHONE||PRIMARIO1__C||PRIMARIO2__C||PRIMARIO3__C||PRIMARIO4__C||PRIMARIO5__C||PRIMARIO6__C||PRIMARIO7__C||PRIMARIO8__C||PROF_COORD_ANAGRAFICHE__C||PROVINCIA_IOL__C||SEDE_PRIMARIA_OPEC__C||TELEFONO_1_ID__C||TELEFONO_2_ID__C||TELEFONO_3_ID__C||TELEFONO_4_ID__C||TELEFONO_5_ID__C||TELEFONO_6_ID__C||TELEFONO_7_ID__C||TELEFONO_8_ID__C||TELEFONO2__C||TELEFONO3__C||TELEFONO4__C||TELEFONO5__C||TELEFONO6__C||TELEFONO7__C||TELEFONO8__C||TIPO_PERSONA_GIURIDICA__C||TIPO_SOCIETA_GIURIDICA__C||TIPOLOGIATELEFONO1__C||TIPOLOGIATELEFONO2__C||TIPOLOGIATELEFONO3__C||TIPOLOGIATELEFONO4__C||TIPOLOGIATELEFONO5__C||TIPOLOGIATELEFONO6__C||TIPOLOGIATELEFONO7__C||TIPOLOGIATELEFONO8__C||TOPONIMO__C||TYPESOC||ULT_POS_AMMINSTRATIVA__C||URL_FANPAGE__C||URL_ID_FANPAGE__C||URL_ID_ISTITUZIONALE__C||URL_ID_PAGINE_BIANCHE__C||URL_ID_PAGINE_GIALLE__C||URL_PAGINE_BIANCHE__C||URL_PAGINE_GIALLE__C||WEBSITE
	INTO cdbRow
	FROM DBACD8ESB.CDB_CONFRONTO_DETT
	WHERE CD02_RUN_GUID = guid
	AND CODICE_CUSTOMER__C = customerId
	AND CODICE_SEDE__C = codiceSede
	AND CD02_TIPO_DIFF = '0'
	AND CD02_SOURCE = 'CDB';
	
	SELECT CASE WHEN sfRow = cdbRow THEN '1' ELSE '0' END INTO result FROM DUAL;
	
    return (result); -- '0' -> diversi, '1' -> uguali
END;
--------------------------------------------------------
--  DDL for Function FORMATNUMBER
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "DBACD8ESB"."FORMATNUMBER" ( param in VARCHAR )
RETURN varCHAR
AS 
    result VARCHAR(200);
BEGIN 

	SELECT param INTO result FROM DUAL;

    IF ( param IS null ) THEN
    BEGIN
    	RETURN NULL;
    END;
    END IF;
    
    IF ( param LIKE '%.0' ) THEN
    BEGIN
    	SELECT substr(param, 0, length(param)-2) INTO result FROM DUAL;
    END;
    END IF;

    return (result); 
END;
--------------------------------------------------------
--  DDL for Function IS_NUMERIC
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "DBACD8ESB"."IS_NUMERIC" ( p_str IN VARCHAR2 )
  RETURN NUMBER
IS
  l_num NUMBER;
BEGIN
  l_num := to_number( p_str );
  RETURN 1;
EXCEPTION
  WHEN value_error
  THEN
    RETURN 0;
END;
--------------------------------------------------------
--  DDL for Function IS_VALID_TRANSACTION
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "DBACD8ESB"."IS_VALID_TRANSACTION" ( raw_xid in tcd0v_rp_gen_sede.cd0v_raw_xid_des%TYPE, prog_trns in tcd0v_rp_gen_sede.cd0v_prog_trns_des%TYPE  )
RETURN CHAR
AS 
    result char;
    conta number;
BEGIN 

    result := '1';

    select count(*) into conta from tcd0v_rp_gen_sede where cd0v_raw_xid_des||cd0v_prog_trns_des = raw_xid||prog_trns;
    if ( conta != 1 ) then
    begin
        return '0';
    end; 
    end if;

    select count(*) into conta from tcd0z_rp_gen_customer where cd0z_raw_xid_des = raw_xid;
    if ( conta != 1 ) then
    begin
        return '0';
    end; 
    end if;

    select count(*) into conta from tcd0v_rp_gen_sede where cd0v_raw_xid_des||cd0v_prog_trns_des = raw_xid||prog_trns 
    and 
        (
            cdl1_stat_cod is null             
        );
    if ( conta > 0 ) then
    begin
        return '0';
    end; 
    end if;

    return (result); -- '1' = OK, '0' = KO

END;
--------------------------------------------------------
--  DDL for Function STATUS_TO_NUMBER
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "DBACD8ESB"."STATUS_TO_NUMBER" 
(
  P_STATUS IN CHAR 
) 
    RETURN NUMBER 
    IS
    status_num NUMBER;  
BEGIN
    
    --'A','D','I','P','Q','R','S','N','O','K'
    
    select 
        case
            when P_STATUS = 'A' then 0
            when P_STATUS = 'D' then 1
            when P_STATUS = 'I' then 2
            when P_STATUS = 'P' then 3
            when P_STATUS = 'Q' then 4
            when P_STATUS = 'R' then 5
            when P_STATUS = 'S' then 6
            when P_STATUS = 'N' then 7
            when P_STATUS = 'K' then 8
            when P_STATUS = 'O' then 9
            else -1 
        end into status_num
    from dual;
    
  RETURN status_num;
END STATUS_TO_NUMBER;
